name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "ruff>=0.5,<1.0" "black>=24.0,<25.0" build
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Build wheel
        run: |
          python -m build
          test -s dist/*.whl
